### ISSUE TITLE
CE3

### ISSUE THREAD

**Issue by TobiasRoland** [cornerman/colibri#165]
Hey! I was working on an `Outwatch` project, and wanted to pull in some new Http4s dependencies, and I got stuck on the classic problem of "you need Cats Effect 3 for this" problem - would it be helpful if I took a crack at upgrading colibri to Cats Effects 3, or is there anything blocking that at the moment?

**Comment by cornerman** [comment]
Hi there! Thanks for opening this issue.

I also really want to upgrade, but there is some blocker in one point of our API. I was hoping to see how monix will handle this, because they kind of have the same problem. But they are for now also stuck on cats-effect 2. It is about methods like (see https://github.com/cornerman/colibri/blob/master/colibri/src/main/scala/colibri/Observable.scala#L138):

```scala
Observable.fromAsync(effect)
observable.mapAsync(_ => effect)
```

Currently we use `cats.effect.Effect` to `runAsync` the effect inside the `subscribe` method of `Observable`.
But `Effect` does not exist anymore in cats-effect 3. We now need a `Dispatcher` and `Async` for our `F`. Then we would probably need an implicit `Dispatcher` for both methods `mapAsync`/`fromAsync`, though that feels a bit wrong. Another alternative would be to pull the effect type into a type parameter of `Observable[T, F[_]]`. That is a bit like fs2. But I feel it also introduces quite some complexity.

One thing, we should also rethink: I feel that the `subscribe` methods really should return an effect type or be called `unsafeSubscribe` in the least, because that is the only side-effecting method on `Observable`.

**Comment by TobiasRoland** [comment]
Yes, `unsafeSubscribe` makes sense to me too. Personally I quite like the fs2 approach because it's very explicit (and I kinda' love fs2) - but I _do_ get the worry about adding additional type parameters to the API.
